SELECT 
F.NOME,
T.NOME AS 'TURMA',
T.CURSO,
T.CODIGO AS 'CODTURMA',
M.STATUS,
CASE
    WHEN T.SERIE BETWEEN 1 AND 2 THEN 'Educação Infantil'
    WHEN T.SERIE BETWEEN 5 AND 9 THEN 'Ensino Fundamental I'
    WHEN T.SERIE BETWEEN 10 AND 13 THEN 'Ensino Fundamental II'
    WHEN T.SERIE BETWEEN 14 AND 16 THEN 'Ensino Médio'
    WHEN T.SERIE BETWEEN 17 AND 19 THEN 'Técnico em Administração'
    WHEN T.SERIE BETWEEN 20 AND 22 THEN 'Técnico em Enfermagem'
    WHEN T.SERIE BETWEEN 23 AND 25 THEN 'Técnico em Informática'
    WHEN T.SERIE BETWEEN 26 AND 28 THEN 'Itinerários Formativos'
    ELSE 'Outros'
END AS 'SEGMENTO',
COUNT(LCAA.FALTA) AS 'FALTAS_TOTAIS_EM_TEMPOS',
CASE 
    WHEN T.SERIE BETWEEN 1 AND 2 THEN 
        CEILING(COUNT(LCAA.FALTA) / 4.0)
    WHEN T.SERIE BETWEEN 5 AND 9 THEN 
        CEILING(COUNT(LCAA.FALTA) / 4.0)
    WHEN T.SERIE BETWEEN 10 AND 13 THEN 
        CEILING(COUNT(LCAA.FALTA) / 4.2)
    WHEN T.SERIE BETWEEN 14 AND 16 THEN 
        CEILING(COUNT(LCAA.FALTA) / 6.0)
    WHEN T.SERIE BETWEEN 17 AND 19 THEN 
        CEILING(COUNT(LCAA.FALTA) / 6.0)
    WHEN T.SERIE BETWEEN 20 AND 22 THEN 
        CEILING(COUNT(LCAA.FALTA) / 6.0)
    WHEN T.SERIE BETWEEN 23 AND 25 THEN 
        CEILING(COUNT(LCAA.FALTA) / 6.0)
    WHEN T.SERIE BETWEEN 26 AND 28 THEN 
        CEILING(COUNT(LCAA.FALTA) / 6.0)
    ELSE COUNT(LCAA.FALTA)
END AS 'FALTAS_TOTAIS_POR_DIA'
FROM sophia.LISTA_CHAMADA_AULA_ALUNO AS LCAA
INNER JOIN sophia.MATRICULA AS M ON M.CODIGO = LCAA.ID_FK_MATRICULA
INNER JOIN sophia.FISICA AS F ON F.CODIGO = M.FISICA
INNER JOIN sophia.LISTA_CHAMADA_AULA AS LCA ON LCA.ID_LISTA_CHAMADA_AULA = LCAA.ID_FK_LISTA_CHAMADA_AULA
INNER JOIN sophia.LISTA_CHAMADA AS LC ON LC.ID_LISTA_CHAMADA = LCA.IDFK_LISTA_CHAMADA
INNER JOIN sophia.TURMAS AS T ON T.CODIGO = LC.IDFK_TURMA
WHERE LCAA.FALTA = 1
AND T.CODIGO IN (:CODTURMA)
AND M.STATUS = '0'
GROUP BY F.NOME, T.NOME, T.CURSO, T.CODIGO, T.SERIE, M.STATUS
ORDER BY FALTAS_TOTAIS_EM_TEMPOS DESC, T.NOME;